# Generated by Django 4.2.23 on 2025-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilianResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('car', 'Car'), ('tractor', 'Tractor'), ('generator', 'Generator'), ('food_supply', 'Food Supply'), ('shelter', 'Shelter'), ('tools', 'Tools')], max_length=50)),
                ('description', models.TextField(help_text='e.g., 4-door sedan, 5kW petrol generator')),
                ('quantity', models.CharField(default='1', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('engineer', 'Engineer'), ('electrician', 'Electrician'), ('mechanic', 'Mechanic')], max_length=50)),
                ('specialty', models.CharField(help_text='e.g., Cardiologist, Diesel engines', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
